services:
  frontend:
    build:
      context: ./mychat
      dockerfile: Dockerfile
    ports:
      - '3000:3000'  # Maps React dev server to port 3000
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps with live reload on Docker
    volumes:
      - ./mychat:/app  # the frontend directory
      - /app/node_modules
    stdin_open: true
    tty: true

  backend:
    build:
      context: ./mychatbackend
      dockerfile: Dockerfile
    ports:
      - '5500:5500'  # Maps Flask to port 5000
    environment:
      - FLASK_ENV=development  # Enable Flask dev environment
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    volumes:
      - ./mychatbackend:/app  # the backend directory
    depends_on:
      - frontend
    stdin_open: true
    tty: true
